theme: minima
title: Muhammad Jahanzeb - CV
minima:
  social_links:
    twitter: szaib1986
    github: jhanzeb12
    stackoverflow: "4793177"
    facebook: me.zaib1987
    linkedin: muhammad-jahanzeb-4b287129
