theme: minima
title: Muhammad Jahanzeb - CV
description: Analytical, technically astute professional with extensive experience managing IT services, developing various websites, and serving as application architect.
minima:
  social_links:
    twitter: szaib1986
    github: jhanzeb12
    stackoverflow: "4793177"
    facebook: me.zaib1987
    linkedin: muhammad-jahanzeb-4b287129
